// Run a copy from a private build directory linked to bundled node_modules.
import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {Presentation, PresentationFile} from '@oai/artifact-tool';
const ROOT=process.env.REPORT_ROOT;
const WORK=process.env.PRESENTATION_BUILD;
const SKILL=process.env.PRESENTATION_SKILL;
const PY=process.env.RUNTIME_PYTHON;
if (![ROOT,WORK,SKILL,PY].every(x=>x&&path.isAbsolute(x))) throw Error('Absolute runtime paths required');
const {finalizePresentation,applyPresentationChartFont}=await import(pathToFileURL(path.join(SKILL,'container_tools/artifact_tool_utils.mjs')));
const M=JSON.parse(await fs.readFile(path.join(ROOT,'sources/verified_metrics.json'),'utf8'));
const FONT='Times New Roman';
const notes=[];
function txt(s,text,x=72,y=170,w=1136,h=95,size=30,bold=false,align='left'){
 const a=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});
 a.text=text;a.text.style={typeface:FONT,fontSize:size,bold,color:'#000000',autoFit:'none',alignment:align};return a;
}
function base(p,n,title,source='Project record through 16 September 2026 · research prototype'){
 const s=p.slides.add();s.background.fill='#FFFFFF';txt(s,`${n}. ${title}`,72,42,1136,98,42,true);
 txt(s,source,72,662,1060,32,18);txt(s,String(n),1150,662,60,30,18,false,'right');return s;
}
function speak(s,n,title,seconds,text){s.speakerNotes.textFrame.setText(`Suggested time: ${seconds} seconds.\n\n${text}`);notes.push({n,title,seconds,text});}
function table(s,caption,values,widths,y=245,height=270){
 txt(s,caption,72,y-65,1136,55,24,true,'center');
 const t=s.tables.add({rows:values.length,columns:values[0].length,left:72,top:y,width:1136,height,columnWidths:widths,values});
 t.borders.assign({style:'solid',fill:'#999999',width:1});
 for(let r=0;r<values.length;r++)for(let c=0;c<values[0].length;c++){
 const cell=t.getCell(r,c);cell.fill=r?'#FFFFFF':'#EEEEEE';cell.text.style={typeface:FONT,fontSize:27,color:'#000000',bold:r===0,alignment:'left',autoFit:'none'};
 }
 return t;
}
const p=Presentation.create({slideSize:{width:1280,height:720}});
let s=base(p,1,'PixelProof: AI image detection');
txt(s,'A working prototype, measured improvements\nand the limits of generalization',72,195,1136,130,40);
txt(s,'Efe Han Keleş · CS395 · Türk Telekom',72,365,1136,65,30,true);
txt(s,'20 July–18 September 2026 · 40 approved internship days',72,440,1136,55,28);
txt(s,'Supervisor: Önder Çelebi, Director\nPlanning and Development Directorate\nComputer Science and Engineering · Sabancı University',72,495,1136,115,26);
txt(s,'Submission date: [TO COMPLETE]',72,618,1136,32,22);
speak(s,1,'Purpose',40,'My supervisor was Önder Çelebi, Director of the Planning and Development Directorate. My internship project was PixelProof, a research prototype for detecting evidence of AI generation in images. I will explain the problem, how the project changed after failures, what the current demo model achieved, and what remains unresolved. The main result is a working local demonstration with substantial improvement on a defined development collection. It is not a universally reliable authenticity detector. The approved internship lasted forty working days. This presentation covers the technical record available before the end of the internship.');
s=base(p,2,'Two tasks, two kinds of evidence');
txt(s,'Model1: Does this image contain AI-generation evidence?',72,185,1136,85,32,true);
txt(s,'False alert: a real photograph receives an AI warning.\nMiss: an AI image escapes detection.',72,287,1136,105,30);
txt(s,'Model2: Where might a local AI edit be?',72,435,1136,65,32,true);
txt(s,'A region map needs its own ground truth and controls.',72,520,1136,70,30);
speak(s,2,'Two tasks',50,'There are two related but different tasks. Model1 evaluates a whole image. We want it to find AI images while avoiding false accusations against real photographs. A false alert and a missed AI image are different errors, and improving one can worsen the other. Model2 tries to localize an edited region. A convincing heatmap is not enough; it must agree with independent edit masks and avoid highlighting authentic regions. We therefore kept localization experimental rather than presenting it as a completed service.');
s=base(p,3,'Strong early scores did not transfer');
txt(s,'Table 1 shows why a familiar test score was only a starting point.',72,164,1136,60,30);
table(s,'Table 1. Early historical accuracy comparisons.',[['Model','Familiar data','External collection'],['Small CNN','96.75%','77.1%'],['ResNet-18','97.66%','25.2%']],[390,340,406],295,210);
txt(s,'Table 1 motivated controls for resolution, source and labels.\nLater audits also qualified the external benchmark.',72,540,1136,90,28);
speak(s,3,'Early failures',60,'Table 1 shows why a high internal score was not enough. The early small CNN achieved about ninety-seven percent on familiar images, but performance fell on an external collection. ResNet improved the familiar score and did much worse externally. A resolution control recovered much of that loss, showing that image preparation mattered. These are historical diagnostics, not final certified results: later auditing also found confounds in the external collection. The important lesson was to investigate what changed before blaming or praising the architecture. Sources: project experiments E1 to E6 and E10.');
s=base(p,4,'Measurement had to be repaired');
txt(s,'Reversed labels\nExplicit source mapping and reruns',72,177,530,150,32,true);
txt(s,'Evaluation-driven threshold\nCalibration-only selection',678,177,530,150,32,true);
txt(s,'Training learns parameters. Calibration chooses the rule.\nDevelopment reveals weaknesses. A final test stays independent.',72,390,1136,115,30);
txt(s,'These roles must remain separate even when files differ.',72,540,1136,70,30,true);
speak(s,4,'Measurement repairs',65,'Two corrections changed the interpretation of earlier work. Some datasets encoded real and AI labels in the opposite direction. We added explicit mappings and reran affected experiments. One DINOv2 result changed from near chance to useful discrimination, so the original explanation was withdrawn. Another audit found that threshold selection could consult evaluation data. Correcting it to use calibration only caused the candidate to fail its admission rule. We retained these failures in the record. Training, calibration, development and final evaluation have different permitted uses. Different files are not automatically independent when they share scenes, prompts or generation ancestry. Sources: E19b, E19c and E27.');
s=base(p,5,'The system combines existing representations');
txt(s,'Pretrained visual features',72,180,1136,60,36,true);
txt(s,'DINOv2 · CLIP · DEAR',72,253,1136,55,32);
txt(s,'Project adaptation',72,350,1136,60,36,true);
txt(s,'Audited data · fitted components · constrained correction',72,423,1136,70,30);
txt(s,'Validated upload → E92 scores → evidence and uncertainty',72,545,1136,65,30,true);
speak(s,5,'Method',65,'The project did not train a foundation model from scratch. Frozen encoders turn an image into numerical descriptions. PixelProof fits additional components and a constrained correction around these features. E92 used twelve thousand two hundred sixty-nine training parent images, with four processing views per parent. More views test processing robustness, but do not create independent photographs. The demo checks the upload, computes original and processed scores, and applies a documented display rule. My responsibilities included directing experiments, organizing sources and reviewing evidence, with AI coding assistance used for implementation and documentation. Research references: Radford et al. 2021, Oquab et al. 2024, Kim et al. 2026 and Ojha et al. 2023.');
s=base(p,6,'Real-image false alerts fell substantially');
txt(s,'Figure 1 compares the same 160 real images per condition.',72,151,1136,55,28);
const chart=s.charts.add('bar',{position:{left:120,top:216,width:1040,height:330},categories:['Original','Social-style JPEG75'],series:[['old','E43 reference','#EEEEEE'],['E86_predecessor','E86','#AAAAAA'],['new','E92','#444444']].map(([key,name,fill])=>({name,fill,values:[M.publisher_original[key].confusion.fp,M.social_q75[key].confusion.fp]})),barOptions:{direction:'column',grouping:'clustered'},hasLegend:true,legend:{position:'bottom',textStyle:{fontSize:22,fill:'#000000',typeface:FONT}},xAxis:{textStyle:{fontSize:22,fill:'#000000',typeface:FONT}},yAxis:{min:0,max:80,majorUnit:20,textStyle:{fontSize:20,fill:'#000000',typeface:FONT}},dataLabels:{showValue:true,position:'outEnd',textStyle:{fontSize:22,fill:'#000000',typeface:FONT}}});
applyPresentationChartFont(chart,{fontFamily:FONT});
txt(s,'Figure 1. False alerts out of 160 real development images.',72,562,1136,45,24,true,'center');
txt(s,'Reused development data · E92 AI detection: 159/160 in each view',72,614,1136,40,24);
speak(s,6,'Main improvement',75,'Figure 1 is the clearest development improvement. All three models are compared on the same real-image parents. For original images, false AI alerts fell from sixty-eight out of one hundred sixty to zero. For the fixed social-style transformation, they fell from sixty-eight to fourteen. That transformation caps the long side at 1080 pixels and applies JPEG quality seventy-five. E92 detected one hundred fifty-nine of one hundred sixty AI images in each condition. This is strong progress on this collection, but zero observed original false alerts does not mean zero future risk. The real images come from only ten SIDD scenes, and these development observations were repeatedly used. Source: evidence/e92_development.json.');
s=base(p,7,'20/20 checks did not mean full acceptance');
txt(s,'Table 2 separates numeric checks from full acceptance.',72,160,1136,65,32,true);
table(s,'Table 2. Two distinct acceptance questions.',[['Question','E92 outcome'],['Numerical development criteria','20/20 passed'],['No newly missed E43-detected AI image','Failed: one original AI image']],[590,546],300,205);
txt(s,'Table 2 explains the limit: better totals can hide a new error.\nThe checks were correlated and were not 20 independent datasets.',72,545,1136,90,28);
speak(s,7,'Acceptance',65,'Twenty out of twenty meant ten numerical requirements checked twice. The requirements covered false alerts, AI recall, balanced accuracy, ranking, coverage and uncertainty. They were project-defined, correlated checks, not an external universal standard. A separate retention rule required that no AI image caught by E43 become a new miss. E92 missed one original AI example that E43 had detected. Recovering other examples did not cancel that loss under the rule. Therefore numerical success and complete acceptance are different conclusions. We should celebrate the improvement without saying the full contract passed.');
s=base(p,8,'The displayed score is not a probability');
txt(s,'Table 3 uses score cuts, not authenticity probabilities.',72,159,1136,70,32,true);
table(s,'Table 3. Simplified E92 display rules.',[['Evidence','User-facing result'],['Original score ≥ upper cut (~7.94)','AI evidence; review warning if needed'],['Both views < lower cut (~1.15)','No clear AI evidence'],['Remaining cases','Uncertain']],[580,556],300,230);
txt(s,'Table 3 does not certify authenticity. E43 is advisory.\nDecisions use unrounded scores; 50% is not the boundary.',72,557,1136,90,28);
speak(s,8,'Scores and demo',85,'The displayed number caused understandable confusion. It is a raw model score multiplied by one hundred, not a probability that a photograph is AI. There is no reason to impose a fifty-percent boundary. The inherited upper cut is approximately seven point nine four; the lower cut is approximately one point one five. An original score above the upper cut keeps an AI alert visible. Two low E92 views produce no clear AI evidence. Other cases remain uncertain, and disagreement can require review. The older reference is advisory and no longer vetoes two low E92 scores. The upper cut came from earlier calibration; the lower cut used previously inspected calibration and development images. They are not fresh E92 calibration or universally optimal values. On the reused development set, the combined website rule left twenty-one real images uncertain and gave no real image an AI alert. It alerted on one hundred fifty-nine AI images and left one uncertain. These are one-result-per-upload counts, unlike the separate-view scores in Figure 1. Guo et al. explain why calibration is a separate question.');
s=base(p,9,'Broader checks exposed remaining weaknesses');
txt(s,'Earlier comprehensive test: E43 failed',72,161,1136,55,33,true);
txt(s,'Real false alerts: 391/1,000 originals; 490/1,000 processed\nDifferent model and population from the E92 comparison',72,227,1136,100,28);
txt(s,'E92 owner gallery: false alerts still occurred',72,357,1136,55,33,true);
txt(s,'9/206 originals; 18/206 processed copies\nPreviously used data, mostly one phone and related scenes',72,422,1136,100,28);
txt(s,'Later candidates also failed full acceptance.',72,563,1136,55,30,true);
speak(s,9,'Broader reliability',90,'The earlier comprehensive E49 test had one thousand real and one thousand AI parents. E43 falsely flagged three hundred ninety-one real originals and four hundred ninety processed views, passing only eleven of twenty checks. Those are E43 results on a different population, not E92 accuracy. E92 did not pass the gate needed to open its E49 regression. Its twenty-out-of-twenty development milestone therefore does not repair or replace that final test. On the owner gallery, E92 produced nine false alerts in two hundred six unique real originals and eighteen after processing. This previously used collection mostly represents one phone. Later E102 reduced development processed false alerts from fourteen to twelve, preserving E92 detections, but retained the same E43-relative miss. It was not promoted. Separate source-fold calibration and source-pixel candidates also failed their requirements. The protected reserves remain unscored, without a verified balanced-final admission. Sources: evidence/e49_final_result.json, E92, E95, E102, E139, E146 and E151.');
s=base(p,10,'Model2 remains an experimental pilot');
txt(s,'Table 4 compares edit placement on 16 previously used images.',72,153,1136,60,29);
table(s,'Table 4. Localization trade-off, original-image condition.',[['Measure','Earlier head','Two-placement head'],['Original-placement pixel AUC','0.74','0.70'],['New-placement pixel AUC','0.57','0.64'],['Authentic falsely flagged area','17.11%','25.74%']],[585,245,306],280,260);
txt(s,'One editor · adaptive development · candidate rejected',72,588,1136,55,29,true);
speak(s,10,'Localization',65,'Model2 illustrates another generalization failure. The earlier head ranked edited pixels reasonably on the original placement, with pixel AUC around zero point seven four. When edits moved, that fell to about zero point five seven. Training on two placements partly recovered performance at the new location, but harmed the original location and increased the area wrongly highlighted in authentic images. Only sixteen previously used original images and one editor were involved. The many transformed maps are not independent samples. Moving an edit also changes its content and generated output, so this is not a pure causal location experiment. Model2 remains separate from the active demo. Sources: E132 through E135.');
s=base(p,11,'A traceable prototype was delivered');
txt(s,'Local web demonstration',72,171,1136,55,34,true);
txt(s,'Validated uploads · clear uncertainty · guarded inference',72,238,1136,65,30);
txt(s,'Reproducible engineering',72,360,1136,55,34,true);
txt(s,'Pinned artifacts · experiment receipts · dataset provenance\nGit history · automated software checks',72,427,1136,110,30);
txt(s,'Latest recorded checkpoint: 1,245 Python tests passed.',72,579,1136,55,29);
speak(s,11,'Deliverables',55,'The outcome includes a trained research system, a local upload interface, experiment commands, aggregate result files and documentation. Software guards handle invalid images, unavailable dependencies, response schema mismatches and cancellation around the heavy inference worker. The artifact manifest is checked before loading the model. The latest recorded checkpoint passed one thousand two hundred forty-five Python tests. These are software assertions, not successful classifications of that many images. No production rollout or company business impact was measured. A reproducible negative result is also a deliverable because it prevents repeating an unsupported claim.');
s=base(p,12,'What the project achieved—and did not');
txt(s,'Table 5 separates implementation success from scientific proof.',72,145,1136,55,28);
table(s,'Table 5. Evidence-supported outcome.',[['Achieved','Still unproven'],['Working student research demo','Universal detection'],['Fewer development false alerts','Independent final-test success'],['Auditable corrections and rejected candidates','Calibrated authenticity probability'],['Controlled localization experiments','Reliable AI-edit localization']],[568,568],275,280);
txt(s,'A credible student prototype with clearly stated limits.',72,592,1136,50,29);
speak(s,12,'Outcome',55,'The prototype is a meaningful student engineering result. It integrates modelling, data handling, software and evaluation. Its strongest improvement is real and reproducible for the specified development population. The equally important limitation is that we have not proved universal detection. Reused data, limited camera scenes, previously seen generator families and unknown pretraining overlap restrict the claim. Model2 also needs much broader evidence. Table 5 is the distinction I would want a reader to remember: building a working system and proving broad reliability are separate achievements.');
s=base(p,13,'The next step is stronger evidence');
txt(s,'Independent sources and resolved ancestry',72,177,1136,65,34,true);
txt(s,'Separate calibration, fixed costs and locked evaluation',72,276,1136,65,32);
txt(s,'Broader cameras, generators, editors and processing',72,375,1136,65,32);
txt(s,'My central lesson: verify what a score actually proves.',72,523,1136,90,36,true);
speak(s,13,'Conclusion',45,'The next priority is an independent evaluation design rather than another impressive number on familiar data. It needs separated sources and ancestry, more cameras and generators, fixed operating costs and calibration that cannot see evaluation outcomes. Localization also needs more editors and authentic controls. My central technical lesson is to verify what a score actually proves. We built a functioning prototype, improved a defined benchmark, corrected mistakes and identified the evidence still missing. Thank you. The following two slides contain references for questions; the full bibliography is in the report.');
s=base(p,14,'Selected references: detection and data','Reference appendix · full bibliographic entries in the report');
const refs1=[['Wang et al. (2020)','CNN-generated images are surprisingly easy to spot… for now. CVPR.'],['Ojha et al. (2023)','Towards universal fake image detectors. CVPR.'],['Grommelt et al. (2024)','Fake or JPEG? arXiv:2403.17608.'],['Abdelhamed et al. (2018)','A high-quality denoising dataset for smartphone cameras. CVPR.'],['Chen et al. (2018)','Learning to see in the dark. CVPR.'],['Keleş (2026)','PixelProof research records, source commit 497d45c. GitHub.']];
refs1.forEach(([a,b],i)=>{txt(s,a,72,155+i*76,1136,32,25,true);txt(s,b,72,187+i*76,1136,39,24);});
speak(s,14,'References A',0,'Backup slide. Full author lists, retrieval dates and direct source links are provided in Section 8 of the report. Project findings are traceable to the evidence map in Appendix 9.2.');
s=base(p,15,'Selected references: features and evaluation','Reference appendix · full bibliographic entries in the report');
const refs2=[['Radford et al. (2021)','Learning transferable visual models from natural language supervision. PMLR.'],['Oquab et al. (2024)','DINOv2: Learning robust visual features without supervision. TMLR.'],['Kim et al. (2026)','Dissect and prune: Enhancing robustness in AI-generated image detection. ICML.'],['Guo et al. (2017)','On calibration of modern neural networks. PMLR.'],['Dwork et al. (2015)','Generalization in adaptive data analysis and holdout reuse. NeurIPS.'],['Türk Telekom (2026a, 2026b)','2025 Annual Report; corporate About Us page.']];
refs2.forEach(([a,b],i)=>{txt(s,a,72,155+i*76,1136,32,25,true);txt(s,b,72,187+i*76,1136,39,24);});
speak(s,15,'References B',0,'Backup slide. Pretrained components do not transfer their published benchmark guarantees to our system. Calibration and adaptive data reuse are separate evaluation problems. Corporate context comes from official Türk Telekom sources.');
const d=Presentation.create({slideSize:{width:1280,height:720}});
s=base(d,1,'PixelProof: AI Image Detection','CS395 digest · source snapshot 497d45c · research prototype');
txt(s,'Türk Telekom · Efe Han Keleş · Computer Science and Engineering',72,147,1136,55,29,true);
txt(s,'20 July–18 September 2026 · 40 approved internship days',72,211,1136,38,27);
txt(s,'Internship office: Fatih Sultan Mehmet Mah., Balkan Cad. No:49,\n34771 Ümraniye / İstanbul',72,255,1136,65,24);
txt(s,'Objective',72,328,260,50,30,true);
txt(s,'Detect AI-image evidence while reducing false alerts;\nexplore localization of AI edits.',360,328,845,90,29);
txt(s,'Deliverables',72,445,260,50,30,true);
txt(s,'E92 research model, guarded local demo and traceable records.\nExperimental Model2 evaluator.',360,445,845,90,29);
txt(s,'Development\nresult',72,535,260,85,30,true);
txt(s,'Reused data: 159/160 AI detected in each condition.\nReal false alerts: 0/160 original; 14/160 processed.\n20/20 checks; one new AI miss blocked full acceptance.',360,535,845,87,25);
txt(s,'Supervisor: Önder Çelebi, Director · Submission date: [TO COMPLETE]',72,628,1136,28,20);
s.speakerNotes.textFrame.setText('Standalone internship digest. Original and social-style views use the same 320 development parents: 160 real and 160 AI. Social-style means long-side cap 1080 followed by JPEG75. E92 newly missed one original AI image caught by E43, so full acceptance failed despite the numeric milestone. Model2 remains experimental. The student confirmed the internship office as Fatih Sultan Mehmet Mah., Balkan Cad. No:49, 34771 Ümraniye / İstanbul on 25 September 2026. Supervisor: Önder Çelebi, Director of the Planning and Development Directorate. Submission date: [TO COMPLETE]. Full sources and limitations are in the report.');
await fs.mkdir(WORK,{recursive:true});
if(process.env.PRESENTATION_KIND!=='Digest') await fs.writeFile(path.join(ROOT,'sources/presentation_notes.json'),JSON.stringify(notes,null,2)+'\n');
for(const [kind,pres,count,tables,charts] of [['Presentation',p,15,[3,7,8,10,12],[6]],['Digest',d,1,[],[]]]){
 if(process.env.PRESENTATION_KIND && process.env.PRESENTATION_KIND!==kind) continue;
 const wd=path.join(WORK,kind);await fs.mkdir(path.join(wd,'.codex-finalizer'),{recursive:true});
 const candidate=path.join(wd,'.codex-finalizer/candidate.pptx');await(await PresentationFile.exportPptx(pres)).save(candidate);
 await fs.mkdir(path.join(wd,'output'),{recursive:true});
 const final=path.join(wd,'output',`CS395_${kind}_EfeHan_Keles_25September2026.pptx`);
 const result=await finalizePresentation({workspaceDir:wd,candidatePath:candidate,finalPath:final,pythonExecutable:PY,integrityValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit',...tables.flatMap(n=>['--require-native-table-slide',String(n)])],requiredNativeTableOwnerSlides:tables,requiredNativeChartOwnerSlides:charts,explicitTotalSlideCount:count,fontPolicy:{basis:'user_request',families:[FONT]},materializeLiteralChartWorkbooks:true,verifyArtifactToolImport:true,receiptPath:path.join(wd,'.codex-finalizer/validation.json')});
 console.log(kind,JSON.stringify({finalPath:result.finalPath,sha256:result.finalSha256,warnings:result.presentationLayout?.warnings}));
 await fs.copyFile(final,path.join(ROOT,'deliverables',path.basename(final)));
}
console.log('Speaking time seconds',notes.reduce((a,n)=>a+n.seconds,0));
