experiment_name: resnet18_genimage_v1
seed: 42
data:
  root: /Users/efehankeles/Desktop/genimage_split
  image_size: 224
  validation_ratio: 0.1
  normalization: imagenet
  crop_augmentation: true
training:
  epochs: 5
  batch_size: 64
  learning_rate: 0.0001
  weight_decay: 0.0001
model:
  name: resnet18
  dropout: 0.0
